import Head from "next/head";
import React from "react";
import Dashboard_ from "../components/Dashboard_";

const Dashboard = () => {
  return (
    <div>
      <Head>
        <title>E-commerce | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard_ />
    </div>
  );
};

export default Dashboard;
