import Login from "../components/Login_";
import Head from 'next/head'

const login = () => {
  return (
    <div>
        <Head>
        <title>E-commerce | Signup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </div>
  );
};

export default login;
