import Register_ from "../components/Register_";
import Head from 'next/head'

const register = () => {
  return (
    <div>
        <Head>
        <title>E-commerce | Signup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Register_ />
    </div>
  );
};

export default register;
