import Head from "next/head";
import React from "react";
import Theme_ from "../components/Theme_";

const theme = () => {
  return (
    <div>
      <Head>
        <title>E-commerce | Themes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Theme_ />
    </div>
  );
};

export default theme;
